[tools]
ruby = "4.0.6"
node = "26.8.2"
go = "1.27.1"
bun = "1.4.2"
zig = "0.16.0"
zls = "0.16.0"
uv = "0.12.13"
protobuf = "36.1"
kubectl = "1.37.0"
helm = "4.3.0"
k9s = "0.51.0"
skaffold = "2.24.0"
stylua = "2.5.2"
tree-sitter = "0.27.0"

[settings]
go.set_gobin = false
