#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..
export ZSH="$(pwd -P)"

# Find the installers and run them in a predictable order.
while IFS= read -r installer
do
  "$installer"
done < <(find . -name install.sh -type f | sort)
